src/Entity/StockTable.php
<?php

namespace App\Entity;

use App\Repository\StockTableRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: StockTableRepository::class)]
class StockTable
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $create_time = null;

    #[ORM\Column(length: 255)]
    private ?string $stock_name = null;

    #[ORM\Column(length: 255)]
    private ?string $stock_price = null;

    #[ORM\Column(length: 255)]
    private ?string $last_update = null;

    #[ORM\Column(length: 150)]
    private ?string $created_by = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreateTime(): ?string
    {
        return $this->create_time;
    }

    public function setCreateTime(string $create_time): self
    {
        $this->create_time = $create_time;

        return $this;
    }

    public function getStockName(): ?string
    {
        return $this->stock_name;
    }

    public function setStockName(string $stock_name): self
    {
        $this->stock_name = $stock_name;

        return $this;
    }

    public function getStockPrice(): ?string
    {
        return $this->stock_price;
    }

    public function setStockPrice(string $stock_price): self
    {
        $this->stock_price = $stock_price;

        return $this;
    }

    public function getLastUpdate(): ?string
    {
        return $this->last_update;
    }

    public function setLastUpdate(string $last_update): self
    {
        $this->last_update = $last_update;

        return $this;
    }

    public function getCreatedBy(): ?string
    {
        return $this->created_by;
    }

    public function setCreatedBy(string $created_by): self
    {
        $this->created_by = $created_by;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\AppListTable;
use App\Entity\StockTable;
use App\Model\HomeModel;
use App\Services\HomeService;
use Doctrine\ORM\EntityManagerInterface;



use Symfony\Component\Form\Extension\Core\Type\SubmitType;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Session\Session;

class HomeController extends AbstractController
{


    /**
     * Instance of Entity Manager interface
     * 
     * @var EntityManagerInterface $em 
     */
    private EntityManagerInterface $em;

    /**
     * Constructor is used to initilize entity manager variabe.
     * 
     * @param object $em 
     * Store the object of EntityManagerInterface Class.
     */
    public function __construct(EntityManagerInterface $em)
    {
        $this->em = $em;
    }

    /**
     * Loads list of stock present in db.
     * 
     * @Route("/home", name="home_page_route")
     * 
     * @param EntityManagerInterFace $entityManager
     * Instance of EntityManagerInterFace
     * 
     * @param Request $request
     * Instance of Request
     * 
     * @return  Response
     * Returns list of available stocks with the response.
     * 
     */
    public function home(EntityManagerInterface $entityManager): Response
    {
        $stock_list_repo = $entityManager->getRepository(StockTable::class);

        //list of all available stocks
        $stock_list = $stock_list_repo->findAll();

        //list of all stocks added by the user.
        $stock_list_user = $stock_list_repo->findBy(['created_by' => 'Bishal@b.com']);

        return $this->render('home/home_page.html.twig',  ['stock_list' => $stock_list, 'stock_list_user' => $stock_list_user]);
    }

    /**
     * Navigate to update page.
     * 
     * @Route("/update_stock_page{stock_id}", name="update_stock_page_route")
     * 
     * @param $stock_id
     */
    public function updateStock($stock_id)
    {
        //...


        return $this->render('home/update_stock.html.twig',  ['stock_id' => $stock_id]);
    }


    /**
     * Naviate to add stock page and add new stock in db
     * 
     * @Route("/add_stock", name="add_stock_page_route")
     * 
     * @param Request $request
     * Instance of request object.
     * 
     */
    public function AddStockPage(Request $request)
    {
        if ($request->isXmlHttpRequest()) {
            $stock = new StockTable();
            $stock->setStockName($request->request->get('name'));
            $stock->setStockPrice($request->request->get('price'));
            $stock->setCreatedBy($_COOKIE['uid']);
            $stock->setLastUpdate("24/04/2023");
            $this->em->persist($stock);
            if ($this->em->flush() == null) {
                $result['status'] = "success";
                $result['message'] = "Stock created successfully";
                setCookie('uid', $request->request->get('email'));
            } else {
                $result['status'] = "failed";
                $result['message'] = "stock creation failed";
            }
            return json_encode($result);
        }

        return $this->render('home/add_stock.html.twig');
    }
}

templates/home/add_stock.html.twig
{% extends 'base.html.twig' %}
{% block title %}Add Stock{% endblock %}
{% block body %}

<div>
Add New Stock
<form name="stock_add_form"  method="post">
<label for="stock_name"></label>
<input type="text" name="stock_name">
<label for="stock_price"></label>
<input type="text" name="stock_price">
<input type="submit" id="action_add_stock">Update</button>
</form>
</div>
{% endblock %}

templates/home/home_page.html.twig
{% extends 'base.html.twig'%}
{% block javascripts %}
	<script src={{ asset("assets/js/home.js") }}></script>
{% endblock %}
{% block title %}
	Home Page
{% endblock %}
{% block body %}


	<div>
		Stocks added by all user

		<table>
			<thead>
				<tr class="flex">
					<td>
						<h2>Stock Name</h2>
					</td>
					<td>
						<h2>Stock Price</h2>
					</td>

				</tr>
			</thead>
			<tbody>
				{% for item  in stock_list %}
					<tr class="flex">
						<td class="title">
							<h2>{{ item.stockName }}</h2>
						</td>
						<td class="desc">
							<h2>{{ item.stockPrice }}</h2>
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>

		<button id="action_add_stock">Add Stock</button>
	</div>
	<br>
	<br><br>
	<div>
		Stocks added by current user
		<table>
			<thead>
				<tr class="flex">
					<td>
						<h2>Stock Name</h2>
					</td>
					<td>
						<h2>Stock Price</h2>
					</td>

				</tr>
			</thead>
			<tbody>
				{% for item  in stock_list_user %}
					<tr class="flex">
						<td class="title">
							<h2>{{ item.stockName }}</h2>
						</td>
						<td class="desc">
							<h2>{{ item.stockPrice }}</h2>
						</td>
						<td>
							<a class="button" href="{{ path('update_stock_page_route', {stock_id: item.id} )}}">Update Stock</a>

						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>

	</div>
{% endblock %}

templates/home/update_stock.html.twig
{% extends 'base.html.twig' %}
{% block title %}Update Stock{% endblock %}

{% block body %}

<div>
Update Stock
<form name="stock_update_form"  method="post">
<label for="stock_name"></label>
<input type="text" name="stock_name">
<label for="stock_price"></label>
<input type="text" name="stock_price">
<button id="action_update_stock" type="submit" >Update</button>
</form>
</div>
{% endblock %}